name: run-test-on-pr
on: 
  push:
    paths:
    - 'frontend/**'
    - '.github/**/main.yml'
    branches:
      - "main"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello, world!"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [16.16.0]
    
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm
    - name: Install Packages
      run: cd frontend && pnpm install
    - name: Build the code
      run: cd frontend && pnpm run build --if-present
